import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// export const metadata = {
//   title: "FEXTEIP",
//   description: "سفری راحت و آسوده",
// }
export const metadata = {
  title: 'Cafe Web App',
  description: 'سفارش آنلاین کافه',
  manifest: '/manifest.json',
  themeColor: '#4CAF50',
  viewport: 'width=device-width, initial-scale=1, maximum-scale=1',
  // موارد اضافی مفید:
  applicationName: 'Cafe Web App',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Cafe Web App',
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    title: 'Cafe Web App',
    description: 'سفارش آنلاین کافه',
    url: 'https://yoursite.com',
    siteName: 'Cafe Web App',
    type: 'website',
  },
  icons: {
    icon: '@/icons/192.png',
    shortcut: '192.png',
    apple: '192.png',
  },
}

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
